# Generated by Django 5.0.4 on 2024-04-24 22:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.TextField(choices=[('cr', 'Experiment created'), ('jo', 'Experiment joined the queue'), ('st', 'Experiment started running'), ('fi', 'Experiment finished successfully'), ('ex', 'Experiment files expired and deleted'), ('fa', 'Experiment did not finish successfully')], default='cr', max_length=2)),
                ('fasta_file', models.TextField()),
                ('annotation_file', models.TextField()),
                ('result_file', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('cr', 'Experiment created'), ('jo', 'Experiment joined the queue'), ('st', 'Experiment started running'), ('fi', 'Experiment finished successfully'), ('ex', 'Experiment files expired and deleted'), ('fa', 'Experiment did not finish successfully')], default='cr', max_length=2)),
                ('date', models.DateTimeField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.job')),
            ],
        ),
    ]
